import type { PersonaKey, PersonaWeights } from "./types";

export const PERSONA_WEIGHTS: Record<PersonaKey, PersonaWeights> = {
  youngPro: {
    housing: 20,
    income: 10,
    safety: 15,
    transport: 20,
    greenSpace: 5,
    noise: 5,
    amenities: 0,
    culture: 10,
    sports: 10,
  },
  family: {
    housing: 25,
    income: 15,
    safety: 25,
    transport: 10,
    greenSpace: 10,
    noise: 15,
    amenities: 15,
    culture: 10,
    sports: 10,
  },
  tourist: {
    housing: 5,
    income: 0,
    safety: 20,
    transport: 15,
    greenSpace: 10,
    noise: 5,
    amenities: 5,
    culture: 20,
    sports: 5,
  },
  business: {
    housing: 15,
    income: 15,
    safety: 15,
    transport: 10,
    greenSpace: 5,
    noise: 5,
    amenities: 10,
    culture: 10,
    sports: 5,
  },
};

export const EQUAL_WEIGHTS: PersonaWeights = {
  housing: 1,
  income: 1,
  safety: 1,
  transport: 1,
  greenSpace: 1,
  noise: 1,
  amenities: 1,
  culture: 1,
  sports: 1,
};
